development:
  adapter: postgresql
  encoding: unicode
  database: twitchoff_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: twitchoff_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: twitchoff_production
  pool: 5
